// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoexumzlmxarkyxgqqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZXh1bXpsbXhhcmt5eGdxcXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODk3NjgsImV4cCI6MjA3NDQ2NTc2OH0.XihtDn5ucthn8tp8nSY0EyRw6wDSEj9XLzmu_yJR7yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});